### ISSUE TITLE
Dokumentaation päivitys kts. kommentit

### ISSUE THREAD

**Issue by UllaMontonen** [UllaMontonen/TicketGuru#127]
https://github.com/mruonavaara/projektikurssi 

Seuraavat asiat tarkistettu/kirjoitettu:
- [x] Roolit ja tarinat
- [x] User interface kuvien päivitys
- [x] Järjestelmän kuvaus
- [ ] Tekninen kuvaus
- [x] Tietokannan kuvaus
- [x] Endpoints: Customers
- [x] Endpoints: Events
- [x] Endpoints: Tickets
- [x] Endpoints: Transactions
- [x] Endpoints: Ticket Types
- [x] Endpoints: Ticket Sales
- [x] Endpoints: Ticket Check
- [x] Authentication: login
- [ ] Authentication: register (jos tehdään)
- [x] Testaussuunnitelma
- [x] Asennustiedot?
- [x] Käynnistys- ja käyttöohje

**Comment by UllaMontonen** [comment]
Valmis dokumentaatio:
- määrittely (roolit, tarinat)
- järjestelmän kuvaus, tietokannan kuvaus.
- API-dokumentaatio
- testausdokumentaatio

**Comment by kridesav** [comment]
TicketSale päivitys

**Comment by UllaMontonen** [comment]
Seuraavat asiat tarkistettu/kirjoitettu:
- [ ] Roolit ja tarinat
- [ ] User interface kuvien päivitys
- [ ] Järjestelmän kuvaus
- [ ] Tekninen kuvaus
- [ ] Tietokannan kuvaus
- [ ] Endpoints: Customers
- [ ] Endpoints: Events
- [ ] Endpoints: Tickets
- [ ] Endpoints: Transactions
- [ ] Endpoints: Ticket Types
- [ ] Endpoints: Ticket Sales
- [ ] Endpoints: Ticket Check
- [ ] Authentication
- [ ] Testaussuunnitelma
- [ ] Asennustiedot?
- [ ] Käynnistys- ja käyttöohje

**Comment by UllaMontonen** [comment]
Jäljellä olevista tehty uudet taskit
