### ISSUE TITLE
Virheenhallinta jatkokehitys (bugien korjaus)

### ISSUE THREAD

**Issue by UllaMontonen** [UllaMontonen/TicketGuru#69]

**Comment by kridesav** [comment]
Jotkut ristiriidat ja validoinnit saattavat vielä aiheuttaa 500 error codee tai antaa väärän kommentin, ainakin yksi mikä tuli vastaan oli kun yrität lippua ostaessa syöttää negatiivisia lukuja lippumäärään, antaa "customer name or email is null" esim.

**Comment by UllaMontonen** [comment]
Selvittelin tätä ja vaikuttaa siltä että Global Exception Handlerin virheilmoitukset tulevat näkyviin virheellisesti muutamassa tapauksessa.

TicketType put komennolla antaa transaction systemin virheen entityjen validoinnin sijaan.

Tickets with id post komento antaa myös transaction systemin virheen kun kyseessä on TicketsDTO validointi. Jos taas muut id validoinit kyseessä niin antaa transaction systemin virheen. Jos tuon kohdalle vaihtaa sen e.getMessage() niin sitten validoi nuo id:t oikein.

Kuitenkaan ticket amount kohtaa ei validoi missään ja antaa mennä läpi vaikka on negatiivinen lippumäärä tai jos se on tyhjä. Ticket DTO luokkaan yritin validointia tehdä, mutta sillä ei ollut mitään vaikutusta tuohohon.

**Comment by UllaMontonen** [comment]
Sellainen myös löytyi, että kun tickets post toiminnoissa lippujenmäärä kyllä validoidaan ensimmäisessä tapahtumassa, mutta jälkimmäisessä myynnissä sitä ei tehdä. Tarkoitan siis sitä että menee jälkimmäisessä läpi vaikka olisi negatiivinen luku.

![Image](https://github.com/UllaMontonen/TicketGuru/assets/92970187/a6472c4d-6520-4353-b2ae-58405bad0e48)



![Image](https://github.com/UllaMontonen/TicketGuru/assets/92970187/258972f0-d41e-4216-9c25-f095654b5b2f)

**Comment by kridesav** [comment]
nämä tapaukset fiksattu
