### ISSUE TITLE
DATE validointi eventtiin

### ISSUE THREAD

**Issue by UllaMontonen** [UllaMontonen/TicketGuru#72]

**Comment by UllaMontonen** [comment]
Yritin tätä selvittää ja sain lisättyä notNull validoinnin tuohon. Heti kun käyttää @Future validointia niin rikkoo koodin. ChatGPT ei osannut tässä myöskään auttaa.

**Comment by UllaMontonen** [comment]
"Date validointi voi taas olla siitä kiinni että se Temporal annotaatio poikkasee siitä kaiken paitsi päivän, kuukauden ja vuoden pois, eikä se validaattori tunnista sitä kunnolla. Mitä luultavammin sen saa toimimaan, jos siihen lisätään Dto objekti väliin missä validointi tapahtuu ja date on normaalissa muodossa"

**Comment by kridesav** [comment]
Lisätty: 
@FutureOrPresent(message = "Date must be in the present or future")

ja commandlinerunnerissa:

Calendar calendar = Calendar.getInstance();
// Add 1 day to the current date
calendar.add(Calendar.DAY_OF_MONTH, 1);
// Convert the Calendar back to a Date
Date date = calendar.getTime();

Testattu postmanissa, jos syöttää: "eventDate": "2023-11-21" niin response on:

{
    "status": "BAD_REQUEST",
    "message": "Validation errors",
    "errors": [
        "Field 'eventDate' Date must be in the present or future"
    ]
}

jos syöttää: "eventDate": "2023-12-21" niin response on:

201 Created

{
    "id": 4,
    "name": "Joulun tähdet -juhlakonsertti",
    "place": "Aleksanterin teatteri",
    "city": "Helsinki",
    "ticketAmount": 1000,
    "eventDate": "2023-12-21T00:00:00.000+00:00"
}

Toivottavasti ei riko jotain muuta :D
